# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snipy.ui'
#
# Created: Mon May 26 01:29:04 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 715)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 191, 681))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView = QtGui.QTreeView(self.horizontalLayoutWidget)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(190, 0, 191, 681))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listView = QtGui.QListView(self.horizontalLayoutWidget_2)
        self.listView.setObjectName("listView")
        self.horizontalLayout_2.addWidget(self.listView)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(380, 90, 451, 591))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit = QtGui.QTextEdit(self.horizontalLayoutWidget_3)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(390, 10, 441, 31))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 22))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtGui.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_E_2 = QtGui.QMenu(self.menubar)
        self.menu_E_2.setObjectName("menu_E_2")
        self.menu_L = QtGui.QMenu(self.menubar)
        self.menu_L.setObjectName("menu_L")
        self.menu_E_3 = QtGui.QMenu(self.menubar)
        self.menu_E_3.setObjectName("menu_E_3")
        self.menu_H = QtGui.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_O = QtGui.QAction(MainWindow)
        self.action_O.setObjectName("action_O")
        self.action_R = QtGui.QAction(MainWindow)
        self.action_R.setObjectName("action_R")
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtGui.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_U = QtGui.QAction(MainWindow)
        self.action_U.setObjectName("action_U")
        self.action_R_2 = QtGui.QAction(MainWindow)
        self.action_R_2.setObjectName("action_R_2")
        self.action_7 = QtGui.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtGui.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtGui.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtGui.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_12 = QtGui.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_M = QtGui.QAction(MainWindow)
        self.action_M.setObjectName("action_M")
        self.action_13 = QtGui.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_14 = QtGui.QAction(MainWindow)
        self.action_14.setObjectName("action_14")
        self.action_15 = QtGui.QAction(MainWindow)
        self.action_15.setObjectName("action_15")
        self.menu_F.addAction(self.action)
        self.menu_F.addAction(self.action_O)
        self.menu_F.addAction(self.action_R)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.action_4)
        self.menu_F.addAction(self.action_5)
        self.menu_F.addAction(self.action_6)
        self.menu_E_2.addAction(self.action_U)
        self.menu_E_2.addAction(self.action_R_2)
        self.menu_L.addAction(self.action_12)
        self.menu_L.addSeparator()
        self.menu_L.addAction(self.action_7)
        self.menu_L.addAction(self.action_8)
        self.menu_L.addAction(self.action_9)
        self.menu_L.addAction(self.action_10)
        self.menu_L.addAction(self.action_15)
        self.menu_E_3.addAction(self.action_M)
        self.menu_E_3.addAction(self.action_13)
        self.menu_H.addAction(self.action_14)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_E_2.menuAction())
        self.menubar.addAction(self.menu_L.menuAction())
        self.menubar.addAction(self.menu_E_3.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_F.setTitle(QtGui.QApplication.translate("MainWindow", "ファイル(&F)", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_E_2.setTitle(QtGui.QApplication.translate("MainWindow", "編集(&E)", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_L.setTitle(QtGui.QApplication.translate("MainWindow", "ライブラリ(&L)", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_E_3.setTitle(QtGui.QApplication.translate("MainWindow", "ウィンドウ(&E)", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_H.setTitle(QtGui.QApplication.translate("MainWindow", "ヘルプ(&H)", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "新しいライブラリ(&N)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_O.setText(QtGui.QApplication.translate("MainWindow", "開く(&O)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_R.setText(QtGui.QApplication.translate("MainWindow", "最近開いたライブラリ(&R)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_4.setText(QtGui.QApplication.translate("MainWindow", "閉じる", None, QtGui.QApplication.UnicodeUTF8))
        self.action_5.setText(QtGui.QApplication.translate("MainWindow", "保存(&S)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_6.setText(QtGui.QApplication.translate("MainWindow", "名前を付けて保存", None, QtGui.QApplication.UnicodeUTF8))
        self.action_U.setText(QtGui.QApplication.translate("MainWindow", "元に戻す(&U)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_R_2.setText(QtGui.QApplication.translate("MainWindow", "やり直す(&R)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_7.setText(QtGui.QApplication.translate("MainWindow", "新しいフォルダ", None, QtGui.QApplication.UnicodeUTF8))
        self.action_8.setText(QtGui.QApplication.translate("MainWindow", "新しいスニペッド", None, QtGui.QApplication.UnicodeUTF8))
        self.action_9.setText(QtGui.QApplication.translate("MainWindow", "新しい画像", None, QtGui.QApplication.UnicodeUTF8))
        self.action_10.setText(QtGui.QApplication.translate("MainWindow", "新しい音声", None, QtGui.QApplication.UnicodeUTF8))
        self.action_12.setText(QtGui.QApplication.translate("MainWindow", "検索", None, QtGui.QApplication.UnicodeUTF8))
        self.action_M.setText(QtGui.QApplication.translate("MainWindow", "縮小(&M)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_13.setText(QtGui.QApplication.translate("MainWindow", "拡大", None, QtGui.QApplication.UnicodeUTF8))
        self.action_14.setText(QtGui.QApplication.translate("MainWindow", "ヘルプ", None, QtGui.QApplication.UnicodeUTF8))
        self.action_15.setText(QtGui.QApplication.translate("MainWindow", "新しい動画", None, QtGui.QApplication.UnicodeUTF8))

